name: Deployment Pipeline in Development

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Lint
        working-directory: ./client
        run: npm run lint
      - name: Test
        working-directory: ./client
        run: npm run test
